/**
 * plan.ts
 * 
 * PURPOSE:
 * TypeScript type definitions for AI-generated execution plans. Defines the structure for
 * step-by-step plans generated by AI services, including plan steps, status tracking, and
 * execution metadata. Used by plan execution components and AI service bridge.
 * 
 * ARCHITECTURE:
 * Plan type system that:
 * - Defines PlanStepType enum (THINK, READ_FILE, CREATE_FILE, EDIT_FILE, DELETE_FILE, RUN_COMMAND)
 * - Defines PlanStep interface with status tracking
 * - Defines Plan interface with steps array and execution state
 * - Defines PlanResponse for API responses
 * - Defines StructuredIdea for idea structuring
 * 
 * CURRENT STATUS:
 * ✅ Plan step types defined
 * ✅ Plan and PlanStep interfaces
 * ✅ Status tracking (pending, running, completed, error)
 * ✅ Execution metadata (timing, errors)
 * ✅ PlanResponse interface
 * ✅ StructuredIdea interface
 * 
 * DEPENDENCIES:
 * - None (standalone type definitions)
 * 
 * STATE MANAGEMENT:
 * - Type definitions only (no state)
 * 
 * PERFORMANCE:
 * - Type-only file (no runtime code)
 * - Efficient type checking
 * 
 * USAGE EXAMPLE:
 * ```typescript
 * import type { Plan, PlanStep, PlanResponse } from '@/types/plan';
 * 
 * const plan: Plan = {
 *   id: 'plan-123',
 *   title: 'Add login page',
 *   status: 'pending',
 *   steps: [
 *     {
 *       id: 'step-1',
 *       type: 'THINK',
 *       status: 'pending',
 *       thought: 'Create login component',
 *     },
 *   ],
 *   currentStep: 0,
 * };
 * ```
 * 
 * RELATED FILES:
 * - src/services/ai/aiServiceBridge.ts: Generates plans
 * - src/components/Workflows/PlanExecutionHost.tsx: Executes plans
 * - src/services/workflow/planExecutionService.ts: Plan execution logic
 * 
 * TODO / FUTURE ENHANCEMENTS:
 * - Parallel step execution types
 * - Step dependencies
 * - Plan templates
 * - Plan validation types
 */
// src/types/plan.ts

export type PlanStepType = 'THINK' | 'READ_FILE' | 'CREATE_FILE' | 'EDIT_FILE' | 'DELETE_FILE' | 'RUN_COMMAND';

export type PlanStepStatus = 'pending' | 'running' | 'completed' | 'error';

export type PlanStatus = 'pending' | 'running' | 'paused' | 'completed' | 'error';

export interface PlanStep {
  id: string;
  type: PlanStepType;
  status: PlanStepStatus;
  thought?: string;
  filePath?: string;
  content?: string;
  command?: string;
  error?: string;
  startTime?: Date;
  endTime?: Date;
  duration?: number;
}

export interface Plan {
  id: string;
  title: string;
  status: PlanStatus;
  steps: PlanStep[];
  currentStep: number;
  createdAt?: Date;
  updatedAt?: Date;
  startTime?: Date;
  endTime?: Date;
  duration?: number;
  error?: string;
}

export interface PlanResponse {
  success: boolean;
  plan?: Plan;
  error?: string;
}

export interface StructuredIdea {
  title: string;
  summary: string;
}

