/**
 * monacoProviders.ts
 *
 * PURPOSE:
 * Monaco Editor provider implementations for LLM-powered features.
 * Registers completion provider, code action provider, and hover provider
 * to enable AI features directly in the editor.
 *
 * FEATURES:
 * - Inline completion provider (Ctrl+Space autocomplete)
 * - Code action provider (lightbulb quick fixes and refactorings)
 * - Hover provider (explanations on hover)
 * - Command to generate code from comments
 */

import type { editor, languages, Position, IRange, CancellationToken } from 'monaco-editor';
import { monacoLLMService } from './monacoLLMService';
import { logger } from '../logging/loggerService';

/**
 * Completion Item Provider - provides autocomplete suggestions
 */
export class LLMCompletionProvider implements languages.CompletionItemProvider {
  triggerCharacters = ['.', '(', ' ', '\n'];

  async provideCompletionItems(
    model: editor.ITextModel,
    position: Position,
    context: languages.CompletionContext,
    token: CancellationToken
  ): Promise<languages.CompletionList | null> {
    try {
      const completion = await monacoLLMService.getInlineCompletion(model, position);

      if (!completion || token.isCancellationRequested) {
        return null;
      }

      const word = model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };

      return {
        suggestions: [
          {
            label: '🤖 AI Suggestion',
            kind: 17, // languages.CompletionItemKind.Snippet
            documentation: 'Generated by local LLM',
            insertText: completion,
            range,
            sortText: '!0', // Show at top of list
            detail: 'LLM-powered completion',
          },
        ],
      };
    } catch (error) {
      logger.error('Completion provider error', { error });
      return null;
    }
  }
}

/**
 * Code Action Provider - provides quick fixes and refactorings
 */
export class LLMCodeActionProvider implements languages.CodeActionProvider {
  async provideCodeActions(
    model: editor.ITextModel,
    range: IRange,
    context: languages.CodeActionContext,
    token: CancellationToken
  ): Promise<languages.CodeActionList | null> {
    try {
      const actions = await monacoLLMService.getCodeActions(model, range);

      if (!actions || actions.length === 0 || token.isCancellationRequested) {
        return null;
      }

      const codeActions = actions.map((action) => ({
        title: `🤖 ${action.title}`,
        kind: action.kind,
        edit: action.edit
          ? {
              edits: [
                {
                  resource: model.uri,
                  textEdit: {
                    range: action.edit.range,
                    text: action.edit.text,
                  },
                },
              ],
            }
          : undefined,
        command: action.command,
      }));

      return {
        actions: codeActions,
        dispose: () => {},
      };
    } catch (error) {
      logger.error('Code action provider error', { error });
      return null;
    }
  }
}

/**
 * Hover Provider - provides explanations on hover
 */
export class LLMHoverProvider implements languages.HoverProvider {
  async provideHover(
    model: editor.ITextModel,
    position: Position,
    token: CancellationToken
  ): Promise<languages.Hover | null> {
    try {
      const explanation = await monacoLLMService.getHoverExplanation(model, position);

      if (!explanation || token.isCancellationRequested) {
        return null;
      }

      return {
        contents: [
          { value: '**🤖 AI Explanation**' },
          { value: explanation },
        ],
      };
    } catch (error) {
      logger.error('Hover provider error', { error });
      return null;
    }
  }
}

/**
 * Register all LLM providers for a Monaco editor instance
 */
export function registerLLMProviders(monaco: typeof import('monaco-editor')): void {
  const supportedLanguages = [
    'typescript',
    'javascript',
    'python',
    'java',
    'go',
    'rust',
    'cpp',
    'c',
    'csharp',
    'html',
    'css',
    'json',
    'sql',
  ];

  // Register completion provider
  supportedLanguages.forEach((language) => {
    monaco.languages.registerCompletionItemProvider(language, new LLMCompletionProvider());
  });

  // Register code action provider
  supportedLanguages.forEach((language) => {
    monaco.languages.registerCodeActionProvider(language, new LLMCodeActionProvider());
  });

  // Register hover provider
  supportedLanguages.forEach((language) => {
    monaco.languages.registerHoverProvider(language, new LLMHoverProvider());
  });

  logger.info('Monaco LLM providers registered', {
    languages: supportedLanguages.length,
  });
}

/**
 * Register editor commands for LLM features
 */
export function registerLLMCommands(
  monaco: typeof import('monaco-editor'),
  editor: editor.IStandaloneCodeEditor
): void {
  // Command: Generate code from comment
  editor.addAction({
    id: 'llm-generate-from-comment',
    label: '🤖 Generate Code from Comment',
    keybindings: [
      monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.KeyG,
    ],
    contextMenuGroupId: 'navigation',
    contextMenuOrder: 1.5,
    run: async (ed) => {
      const model = ed.getModel();
      const position = ed.getPosition();

      if (!model || !position) return;

      try {
        const code = await monacoLLMService.generateFromComment(model, position);

        if (code) {
          ed.executeEdits('llm-generate', [
            {
              range: {
                startLineNumber: position.lineNumber + 1,
                startColumn: 1,
                endLineNumber: position.lineNumber + 1,
                endColumn: 1,
              },
              text: '\n' + code + '\n',
            },
          ]);

          logger.info('Code generated from comment');
        }
      } catch (error) {
        logger.error('Generate from comment failed', { error });
      }
    },
  });

  // Command: Clear LLM cache
  editor.addAction({
    id: 'llm-clear-cache',
    label: '🤖 Clear LLM Cache',
    keybindings: [],
    contextMenuGroupId: '9_cutcopypaste',
    contextMenuOrder: 5,
    run: () => {
      monacoLLMService.clearCache();
      logger.info('LLM cache cleared via command');
    },
  });

  logger.info('Monaco LLM commands registered');
}

/**
 * Configure Monaco editor for optimal LLM experience
 */
export function configureLLMSettings(editor: editor.IStandaloneCodeEditor): void {
  editor.updateOptions({
    // Enable suggestions
    quickSuggestions: {
      other: true,
      comments: false,
      strings: false,
    },
    suggestOnTriggerCharacters: true,
    acceptSuggestionOnCommitCharacter: true,
    acceptSuggestionOnEnter: 'on',
    tabCompletion: 'on',

    // Suggestion behavior
    suggestSelection: 'first',
    suggestFontSize: 13,
    suggestLineHeight: 20,

    // Code action (lightbulb) settings
    lightbulb: {
      enabled: true,
    },

    // Hover settings
    hover: {
      enabled: true,
      delay: 300,
      sticky: true,
    },

    // Performance
    wordBasedSuggestions: false, // Rely on LLM instead
  });

  logger.info('Monaco editor configured for LLM features');
}
