import React, { createContext, useContext, useState, useCallback, ReactNode } from 'react';
import { CheckCircle2, XCircle, AlertCircle, Info, X } from 'lucide-react';
import { Button } from './Button';
import '../../styles/ui/Toast.css';

export type ToastVariant = 'success' | 'error' | 'warning' | 'info';

export interface Toast {
  id: string;
  title?: string;
  message?: string; // Made optional - can use title+description instead
  description?: string; // Optional description for more detailed toasts
  variant: ToastVariant;
  duration?: number;
  action?: {
    label: string;
    onClick: () => void;
  };
}

interface ToastContextType {
  showToast: (toast: Omit<Toast, 'id'>) => void;
  removeToast: (id: string) => void;
}

const ToastContext = createContext<ToastContextType | undefined>(undefined);

/**
 * Hook returning toast helpers provided by `ToastProvider`.
 *
 * @throws Error if used outside of provider scope.
 */
export const useToast = () => {
  const context = useContext(ToastContext);
  if (!context) {
    throw new Error('useToast must be used within ToastProvider');
  }
  return context;
};

/**
 * Context provider that manages toast notifications and renders the container UI.
 *
 * @param props.children - Application subtree receiving toast context.
 * @returns Provider wrapping children with toast functionality.
 */
export const ToastProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [toasts, setToasts] = useState<Toast[]>([]);

  /**
   * Create a toast with autogenerated id and optional auto-dismiss timer.
   *
   * @param toast - Toast configuration without id.
   */
  const showToast = useCallback((toast: Omit<Toast, 'id'>) => {
    const id = `toast-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    const newToast: Toast = {
      ...toast,
      id,
      duration: toast.duration ?? 5000,
    };

    setToasts((prev) => [...prev, newToast]);

    if (newToast.duration && newToast.duration > 0) {
      setTimeout(() => {
        removeToast(id);
      }, newToast.duration);
    }
  }, []);

  /**
   * Remove a toast by id.
   *
   * @param id - Identifier of the toast to remove.
   */
  const removeToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((toast) => toast.id !== id));
  }, []);

  return (
    <ToastContext.Provider value={{ showToast, removeToast }}>
      {children}
      <ToastContainer toasts={toasts} onRemove={removeToast} />
    </ToastContext.Provider>
  );
};

interface ToastContainerProps {
  toasts: Toast[];
  onRemove: (id: string) => void;
}

/**
 * Render active toasts in a stack with polite aria announcements.
 *
 * @param props - Toast collection and remove handler.
 * @returns Toast list container or null when empty.
 */
const ToastContainer: React.FC<ToastContainerProps> = ({ toasts, onRemove }) => {
  if (toasts.length === 0) return null;

  return (
    <div className="ui-toast-container" role="region" aria-live="polite" aria-label="Notifications">
      {toasts.map((toast) => (
        <ToastItem key={toast.id} toast={toast} onRemove={onRemove} />
      ))}
    </div>
  );
};

interface ToastItemProps {
  toast: Toast;
  onRemove: (id: string) => void;
}

/**
 * Individual toast notification with icon, message, optional action, and close button.
 *
 * @param toast - Toast data to render.
 * @param onRemove - Callback invoked to dismiss the toast.
 * @returns Toast UI element.
 */
const ToastItem: React.FC<ToastItemProps> = ({ toast, onRemove }) => {
  const icons = {
    success: CheckCircle2,
    error: XCircle,
    warning: AlertCircle,
    info: Info,
  };

  const Icon = icons[toast.variant];

  return (
    <div
      className={`ui-toast ui-toast--${toast.variant}`}
      role="alert"
      aria-live="assertive"
    >
      <div className="ui-toast__icon">
        <Icon size={20} />
      </div>
      <div className="ui-toast__content">
        {toast.title && <div className="ui-toast__title">{toast.title}</div>}
        <div className="ui-toast__message">{toast.message}</div>
        {toast.action && (
          <Button
            variant="ghost"
            size="sm"
            onClick={toast.action.onClick}
            className="ui-toast__action"
          >
            {toast.action.label}
          </Button>
        )}
      </div>
      <Button
        variant="ghost"
        size="sm"
        onClick={() => onRemove(toast.id)}
        className="ui-toast__close"
        aria-label="Close notification"
      >
        <X size={16} />
      </Button>
    </div>
  );
};

